Ainda falta testar

@token = INSIRA_SEU_TOKEN_JWT_AQUI

### 1. Criar um novo insumo
POST http://localhost:3000/insumos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Aço Inoxidável 304",
  "tipo": "Materia-prima",
  "unidade": "Kg",
  "descricao": "Chapa de aço inox 2mm",
  "quantidade": 100,
  "precoUnit": 25.50,
  "alertaMinimo": 20,
  "fornecedor": "Metalúrgica Global"
}

### 2. Listar todos os insumos
GET http://localhost:3000/insumos
Authorization: Bearer {{token}}

### 3. Buscar um insumo por ID (Substitua pelo ID gerado na criação)
GET http://localhost:3000/insumos/ID_AQUI
Authorization: Bearer {{token}}

### 4. Atualizar dados de um insumo (Substitua pelo ID gerado)
PATCH http://localhost:3000/insumos/ID_AQUI
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "quantidade": 120,
  "precoUnit": 26.00
}

### 5. Excluir um insumo (Substitua pelo ID gerado)
DELETE http://localhost:3000/insumos/ID_AQUI
Authorization: Bearer {{token}}
